MODE_BW = '1'
WIDTH = 480
HEIGHT = 800
SIZE = (WIDTH, HEIGHT)
DEFAULT_COLOR = 1  # white
INK_COLOR = 0  # black
PADDING_DEFAULT = 10

DATETIME_SIZE = (WIDTH -2 * PADDING_DEFAULT, 150)
STM_PANEL_SIZE = (WIDTH -2 * PADDING_DEFAULT, 150)
METEO_PANEL_SIZE = (WIDTH - 2 * PADDING_DEFAULT, 150)
NBA_PANEL_SIZE = (WIDTH - 2 * PADDING_DEFAULT, 100)