IMG_MODE = '1'

WIDTH = 480
HEIGHT = 800
SIZE = (WIDTH, HEIGHT)

GRAY1 = WHITE = 0xff
GRAY2  = 0xC0
GRAY3  = 0x80
GRAY4 = BLACK = 0x00

PADDING_DEFAULT = 10

DATE_SIZE = (WIDTH -2 * PADDING_DEFAULT, 50)
DATETIME_SIZE = (WIDTH -2 * PADDING_DEFAULT, 150)
MESSAGE_SIZE = (WIDTH -2 * PADDING_DEFAULT, 50)
STM_PANEL_SIZE = (WIDTH -2 * PADDING_DEFAULT, 150)
METEO_PANEL_SIZE = (WIDTH - 2 * PADDING_DEFAULT, 150)
NBA_PANEL_SIZE = (WIDTH - 2 * PADDING_DEFAULT, 100)
LIBRARY_PANEL_SIZE = (WIDTH - 2 * PADDING_DEFAULT, 104)